name: CI

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:
  test:
    name: python test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.15"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: run tests
        run: uv run python control_systems.py